name: Test Workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test step
      run: |
        echo "GitHub Actions is working!"
        echo "Current directory: $(pwd)"
        echo "Files in root:"
        ls -la
        echo "Files in .github/workflows:"
        ls -la .github/workflows/ 